---
- name: Playbook for install strongswan vpn
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - role: strongswan
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"